# Generated by Django 4.2 on 2024-05-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataExtraction', '0002_remove_ibgechildattached_territorial_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IBGETerritorialLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('administrative', 'Administrative'), ('special', 'Special'), ('ibge', 'IBGE')], max_length=15, null=True)),
                ('territorial_id', models.CharField(max_length=10)),
                ('territorial_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ibgechildattached',
            name='territorial_level',
            field=models.ManyToManyField(to='dataExtraction.ibgeterritoriallevel'),
        ),
    ]
